pawsapp/urls.py
from django.urls import path
from . import views

app_name = 'pawsapp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('get_deets', views.get_deets, name='get_deets'),
    path('references/', views.references, name ='references'),
    path('contact/', views.contact, name = 'contact'),
]

pawsitivefocus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pawsapp.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern
from . import views

app_name= 'users'

urlpatterns =[
    path('', views.index, name='index'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('log_out/', views.log_out, name= 'log_out'),
    path('personal_profile/', views.personal_profile, name='personal_profile'),
    path('personal_profile/update_dog/', views.update_dog, name='update_dog'),
    path('personal_profile/update_user/', views.update_user, name='update_user'),
    path('personal_profile/new_dog/', views.new_dog, name = 'new_dog'),
    path('personal_profile/dog_deleter/', views.dog_deleter, name= 'dog_deleter')
]

pawsapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.utils import timezone
from users.models import UserProfile, Dog


# Create your models here.

class Appointment(models.Model):

    created_at = models.CharField(max_length = 100, default = timezone.now())
    replied_to = models.BooleanField(default=False)
    owner = models.CharField(max_length=100)
    email = models.EmailField(max_length= 50,blank=True, null=True)
    address= models.CharField(max_length= 50, blank=True, null=True)
    city = models.CharField(max_length= 50, blank=True, null=True)
    phone = models.CharField(max_length= 50, blank=True, null=True)
    puppy_training = models.BooleanField(default=False)
    adolescent_training = models.BooleanField(default=False)
    adult_training = models.BooleanField(default=False)
    dog_detail = models.CharField(max_length=500, blank=True, null=True)
    heard_about = models.CharField(max_length=100, default='Google')
    dog_name = models.CharField(max_length=50, blank=True, null=True)
    req_appt1 = models.DateTimeField( blank=True, null=True )
    req_appt2 = models.DateTimeField( blank=True, null=True)
    req_appt3 = models.DateTimeField( blank=True, null=True)

    

    def __str__(self):
        return  f'{self.email}: {self.dog_name}'

pawsapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.http import HttpResponse
from .models import Appointment
from django.utils import timezone
from django.utils.timezone import is_aware, make_aware
from datetime import datetime, time
from django.core.mail import send_mail
from decouple import config
import os
# Create your views here.

def index(request):
    
    return render(request, 'pawsapp/index.html')
    

def get_deets(request):
    
    if request.POST:
        form = request.POST
        owner = form['first_name'] + " " + form['last_name']


        if not form.get('first_name') or not form.get('email') or not form.get('phone'):

            return render(request, 'pawsapp/customer_form.html', {'info': 'Please Enter Information Into All Required Fields.'})
            




       
        owner = owner
        email = form['email']
        address = form['address']
        city = form['city']
        phone = form['phone']
        puppy_training = bool(form.get('puppy_training'))
        adolescent_training = bool(form.get('adolescent_training'))
        adult_training = bool(form.get('adult_training'))
        dog_name = form['dog_name']
        dog_detail = form["dog_detail"]
        heard_about = form.get('heard_about',None)
        adoption = form.get('referred',None)
        other = form.get('other',None)
        referred = 'None'

        time1 = form.get('time1')
        time2 = form.get('time2')
        time3 = form.get('time3')
        error_message = None

        if time1:
            try:
                time1 = datetime.strptime(time1,'%Y-%m-%dT%H:%M' ) 
                time1_aware = make_aware(time1)


            except:
                error_message='Please Select a Time'
                time1 = None
        
        else:
            error_message= 'Please Select a Time'
            time1 = None


        if time2:
            try:
                time2 = datetime.strptime(time2,'%Y-%m-%dT%H:%M' )
                time2_aware = make_aware(time2)

            except ValueError:
                error_message = 'Invalid Input'
                time2 = None

        else:
            time2 = None

        
        
        if time3:
        
            try:
                time3 = datetime.strptime(time3,'%Y-%m-%dT%H:%M' )
                time3_aware = make_aware(time3)

            except ValueError:
                time3 = None
                
        else:
            time3 = None

        
        if time1:

            if time1 < datetime.now():
                
                return render(request, 'pawsapp/customer_form.html', {'info': 'Please Enter a Time in the future.'})









        heard_about = 'None Selected'

        if heard_about != 'Other' and heard_about != 'Referral' and heard_about != None:
            referred = heard_about
        elif adoption:
            referred = adoption
        elif other:
            referred = other
        else:
            referred = 'None Selected'


        customer = Appointment(
            owner = owner,
            email = email,
            address = address,
            city = city,
            phone = phone,
            dog_name= dog_name,
            puppy_training = puppy_training,
            adolescent_training = adolescent_training,
            adult_training =adult_training,
            dog_detail =dog_detail,
            heard_about = referred,
            req_appt1 = time1_aware,
            req_appt2 = time2,
            req_appt3 = time3,
        )

        customer.save()
        send_mail(
                    'Appointment Created!',
                    f'Person: {owner} \n {email} \nDog: {dog_name} \nTime Created: {datetime.now()} \nDetails: {dog_detail}\nSee the ADMIN Panel for more information',
                    'from@yourdjangoapp.com',
                    ['tadashicroy@gmail.com'],
                    fail_silently=False,
                )

        context = { 
            'dog_name': form['dog_name'],
            'info': error_message,


            }
        
        return render(request, 'pawsapp/customer_form.html', context)

    else:
        form =''

    return render(request, 'pawsapp/customer_form.html') 


def references(request):


    return render(request, 'pawsapp/references_page.html')



def contact(request):

    return render(request, 'pawsapp/contact.html')

pawsapp/templates/pawsapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static%}
    <link rel="stylesheet" href="{% static 'pawsapp/style.css'%}">
    <script defer src="{% static 'pawsapp/main.js' %}"></script>
    <script src="https://kit.fontawesome.com/cdc9299abe.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js" integrity="sha512-quHCp3WbBNkwLfYUMd+KwBAgpVukJu5MncuQaWXgCrfgcxCJAq/fo+oqrRKOj+UKEmyMCG3tb8RB63W+EmrOBg==" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Montserrat:ital,wght@0,400;0,500;1,400;1,500&family=Yanone+Kaffeesatz&display=swap" rel="stylesheet">
    <title>
        {% block title%}
        {% endblock %}</title>

</head>
<body>
    
    <header id="base-head">
        <div class="hero"> 
            <h2>
            <a href="{% url 'pawsapp:index' %} ">
                
                    Pawsitive Focus Dog Training
                </a>
                </h2>

            
            <!-- <a href="mail: test@test.com"> <button> Contact</button></a>   -->

        
        </div>

        <div class="header-links">
            
            <a href="{% url 'pawsapp:index' %} ">
                Home
            </a>
            <a href="{% url 'pawsapp:contact' %} ">
                Contact Us
            </a>
            
            {% if not user.is_authenticated %}
            
            
            {% else %}
            
            <a href="{% url 'pawsapp:get_deets' %}">
                Book Appointment
            </a>

            <!-- Add Later! -->
            <!-- All I did was move below the if statement -->


            <a href=" {% url 'users:sign_up' %}">
                Sign Up
            </a>
            
            <a href="{% url 'users:log_in' %}">
                Log In
            </a>
            
            
            <a href="{% url 'users:personal_profile' %}">Profile Page</a>


            <a href="{% url 'users:log_out' %}">
                Log Out
            </a>

            {% endif %}

            <a href="{% url 'users:index' %}">
                About Me
            </a>
            
            

           
            <a href="{% url 'pawsapp:references' %}">
                References

            </a>

        </div>



    </header>


    <hr>
    <div id="app">
        
        {% block content %}
        
        {% endblock %}
        
    </div>

    {% block extra %}

    {% endblock %}
    <div class="extra-space">

    </div>
    
    
    
    <footer>
        
        <div class="contact-info">
            <div >
                <p class="info-top" >Kellyn Croy</p>
                <p class="info-top" > <em>Pawsitive Focus Dog Training</em> </p>
                <br>    
                <p><i class="far fa-envelope"></i>
                    
                    <a id="mail" href="mailto:kcroy@pawsitivefocusdogtraining.com">kcroy@pawsitivefocusdogtraining.com</a> 
                </p>

                <p>
                    <i class="fas fa-mobile-alt"></i>
                    Tel: (971) 206-1489
                </p>
            </div>
            <div class="font-awesome-imgs">

                <a href="https://www.facebook.com/PawsitiveFocusDogTraining/" target="_blank">
                    <i class="fab fa-facebook"></i>
                </a>
                <a href="https://pawsitivefocus.blog/" target="_blank">
                    <i class="fab fa-wordpress"></i>
                </a>
                <a href="https://www.instagram.com/pawsitivefocus/" target="_blank">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>
            
            <div>
                <img id="apdt-img" src="{% static 'pawsapp/images/APDT-logo-300x294.jpg' %}" alt="APDT Image">
                <img id='ccdt-img' src="{% static 'pawsapp/images/CATCH_CCDT-Seal-Blue-300.jpg' %}" alt="">
                <img id='bite-img' src="{% static 'pawsapp/images/Dog_Bite_Safety_Educator_Badge.jpg' %}" alt="">

            </div>


        </div>
        <div class="cert">
            Certified by:
            <a href="https://catchdogtrainers.com/who-we-are/" target="_blank">
               <strong>
                   Catch Dog Trainers
               </strong>
            </a>
            <p>Pawsitive Focus Dog Training 2020&trade;</p>
            
        </div>
        
    </footer>

</body>
</html>

pawsapp/templates/pawsapp/contact.html
{% extends 'pawsapp/base.html' %}
{% load static%}

{% block title%}

Contact Us!

{% endblock %}

{% block content %}

    <div class="contacts">

        <div class="contact-body">

            <img src="{% static 'pawsapp/images/contact.JPG' %}" alt="">

            <p>

            </p>
        </div>

        <div class="contact-body-info">                
            <a id="mail" href="mailto:kcroy@pawsitivefocusdogtraining.com">kcroy@pawsitivefocusdogtraining.com</a> 
            
            <p>
                (971) 206-1489
            </p>
            <br>
            <p>Check Us Out On:</p>
            <ul class="contact-links">
                <li>
                    <a href="https://www.facebook.com/PawsitiveFocusDogTraining/" target="_blank">
                        Facebook
                    </a>
                </li>
                <li>
                    <a href="https://pawsitivefocus.blog/" target="_blank">
                        Word Press Blog
                    </a>
                </li>
                <li>
                    <a href="https://www.instagram.com/pawsitivefocus/" target="_blank">
                        Instagram
                    </a>
                </li>
            </ul>
        </div>
            
        <div>

        </div>

    </div>

{% endblock %}

pawsapp/templates/pawsapp/customer_form.html
{% extends 'pawsapp/base.html' %}
    
{% block title%}

Appointments

{% endblock%}



{% block content%}
<main class="customer-form-body">
        <div class="customer-form-header">

            <p>Book An Appointment <span class="customer-form-spanner">(Or Start A Conversation)</span> :</p>

            {% if info  %}
            <h4>{{info}}

                {% if dog_name%}
                for {{dog_name}}
                {% endif %}
            </h4> 

            {% endif %}
        </div>
        <div class="customer-form">

            <form action="{% url 'pawsapp:get_deets'%}" method="post">
                {% csrf_token%}
                
                <div class="entry">



                    <div class="basic-info">
                        <div>
                            <label for="first_name"> First Name<span class="required">*</span></label>
                            <input  name="first_name" type="text" placeholder="Enter First Name">
                        </div>
                        
                        <div>
                            <label for="last_name"> Last Name<span class="required">*</span></label>
                            <input name= "last_name" type="text" placeholder="Enter Last Name">
                        </div>

                        <div>
                            <label for="email"> Email Address<span class="required">*</span></label>
                            <input type="email" name="email" id="email" placeholder="Enter email address">
                        </div>
                        
                        <div>
                            <label for="address"> Enter Street Address</label>
                            <input type="text" name="address" id="" placeholder="Street Address">
                        </div>

                        <div>
                            <label for="city"> Enter City</label>
                            <input type="text" name="city" id="" placeholder="City" >
                        </div>

                        <div>
                            <label for="phone"> Enter Phone Number<span class="required">*</span></label>
                            <input name = 'phone' type="tel" placeholder="Enter Phone Number">
                        </div>

                    </div>


                    <div class="training-checks">
                        <div>
                            <input type="checkbox" name="puppy_training" id="" value="True">
                            <label for="puppy_training"> Puppy training</label>
                        </div>
                        
                        <div>
                            <input type="checkbox" name="adolescent_training" id="" value="True">
                            <label for="adolescent_training">Adolescent Training</label>
                        </div>
                        
                        <div>
                            <input type="checkbox" name="adult_training" id="" value="True">                    
                            <label for="adult_training">Adult Dog Training</label>
                        </div>

                    </div>  
                        
                    <div class=" appt-times">
                        <h5>Enter up to three convienient dates and times for the training sessions or consultation:</h5>
                        
                        <div class="time">
                            <label for="time1"> First Choice <span class="required">*</span>:</label>
                            <input type="datetime-local" name="time1" id="time1" placeholder="Time 1">
                            
                        </div>
                        <div class="time">
                            <label for="time2"> Second Choice:</label>
                            <input type="datetime-local" name="time2" id="time2" placeholder="Time 1">
                            
                        </div>
                        <div class="time">
                            <label for="time3">Third Choice:</label>
                            <input type="datetime-local" name="time3" id="time3">
                            
                        </div>
                        
                    </div>
                   
                    
                    
                    
                    
                    <div class="dog-details">
                        <div class="dog-name">
                            <label for="dog_name"> Dog Name</label> <br>
                            <input type="text" name="dog_name" id="" placeholder="Name of Dog">
                        </div>

                        <textarea name="dog_detail" id="" cols="20" rows="5" placeholder="Tell me about your dog or what you'd like to discuss..." ></textarea>
                    </div>
                    
                    <div class="referred-by">

                        <select v-model="heardAbout" name="heard_about" id="">  
                            
                            <option value="" disabled>How did you hear about us?</option>
                            <option value="Google">Google</option>
                            <option value="Facebook">Facebook</option>
                            <option value="Local Adoption">Local Adoption Agency</option>
                            <option value="Rover">Rover</option>
                            <option value="Referral">Personal Referral</option>
                            <option value="Other">Other</option>
                            
                            
                        </select>
                        
                        
                        <div v-if="heardAbout">
                            <input v-if="heardAbout === 'Referral' " type="text" name="referred" id="referred" placeholder= 'Referred by?'>
                            <input v-if="heardAbout === 'Other' " type="text" name="other" id="other" placeholder="Enter Other Method">
                            
                        </div>
                        
                    </div>
                    
                    
                        
                </div>
                    
                
                <div class="submit-btn" > 

                    <input type="submit" value="Submit">
                </div>
                <br>
                <p> <span class="required">*</span> Indicates a required field</p>
            </form>
        </div>
            
            
            
            
            
    </main>
{% endblock %}

pawsapp/templates/pawsapp/googleaaec7a7c344fa340.html
google-site-verification: googleaaec7a7c344fa340.html

pawsapp/templates/pawsapp/index.html
{% extends 'pawsapp/base.html'  %}
{% load static %}

{% block title%}
Pawsitive Focus Dog Training
{% endblock %}
{% block content%}

<div class="index-body app">

    <div class="hero-pic">
        <div>
            <q>
                Training with a positive focus is fun and builds an unbreakable bond between dog and handler.
                A fulfilled, confident dog enjoys being well behaved and has a strong desire to learn! 
            </q>
        </div>
    </div>



    <div class="index-content">

        
        <div class="index-content-div">

            <div class="index-intro">

                <h4>Welcome!</h4>
                
                <p>My name is Kellyn and I'm a certified Dog Trainer with CATCH dog trainers</p>
            </div>




            <div class="service-intro">
                <p>
                    Services
                </p>
                <h6 class="update">
                    All consults will be done over Zoom. Lesson locations will be determined during the video call. 
                    Discounts available for rescue dogs, foster dogs, and shelter dogs. 
                </h6>

            </div>

            <main class="service-holder">

                <div class="service i1"> <span class="spanner" > Walk and Train </span> 
                <img src="{% static 'pawsapp/images/walk_and_train.jpg' %}" alt="">
                <p>
                    I come to your home and take your dog for a daytime 30 - 60 minute walk providing exercise and training. 
                    This is a great service for those with energetic or unruly dogs! I leave you daily reports with your dog’s 
                    progress and the techniques that I am using so that you can implement them as well. Prices start at $25/walk.
                </p>
                
                </div> 
               
                <div class="service i2"> <span class="spanner"> Puppy Training </span> 
                    <img src="{% static 'pawsapp/images/puppy_training.jpg '%}" alt="">
                    <p>
                        One on one training sessions for puppies. Length of session 
                        depends on needs but not to exceed 60 minutes. Prices start at $60/session. 
                    </p>
                
                </div> 
                <div class="service i3"> <span class="spanner">Private Enrichment and Training</span>  
                    <img src="{% static 'pawsapp/images/private_lessons.jpg' %}" alt="">
                    <p>
                        I come to your home during the day and provide enrichment, mental stimulation, 
                        basic training, and a bathroom break for your dog for 20 – 45 minutes while you are out.
                        You’ll come home to a calmer, happier dog whose skills are being developed and maintained. 
                        I leave you daily reports with the activities we did and the training techniques we practice 
                        so that you can implement them as well. Prices start at $20/visit.
                    </p>
                </div>
                <div class="service i4"> <span class="spanner"> Group Classes</span> 
                    <img src="{% static 'pawsapp/images/group_classes.jpg '%}" alt="">
                    <p>
                        <!-- Need help socializing your dog? This is the class for you! Its easy for us to forget that
                        dogs need other dogs to remember how to interact with them. This class is especially helpful 
                        for our leash-reactive buds! -->
                        Unfortunately Group Classes are on hold for the time being.
                    </p>
                </div>
                <div class="service i5 big-img"> <span class="spanner" >Private lessons </span> 
                    <img src="{% static 'pawsapp/images/sammy.jpg '%}" alt="">
                    <p>
                        One on one training sessions for adolescent and adult dogs. 
                        Length of session depends on needs but not to exceed 90 minutes.
                         Prices start at $60/session.
                    </p>
                    
                </div> 
        
                <div class="service i6"> <span class="spanner" > Pack walks </span> 
                    <img src="{% static 'pawsapp/images/pack.jpg '%}" alt="">
                    <p>
                        Group pack walks are for friendly or mildly reactive dogs. This is a great opportunity 
                        for socialization! I will briefly teach clicker training as a 
                        positive way to teach leash walking skills with clarity your dog will understand. 
                        The price is $10/walk. 
                    </p>
                    
                </div>     
                
            </main>
        
            
         
            
        </div>


        </div>
            
        
        
    </div>
    
</div>

{% endblock %}

{% block extra%}
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>

<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>


<div class="extra-space"></div>
<div class="extra-space"></div>
{% endblock %}

pawsapp/templates/pawsapp/references_page.html
{% extends 'pawsapp/base.html' %}

{% block title%}

References

{% endblock %}

{% block content %}
<div class=" reference-page-body">

    <div class="heart h0"></div>
    <div class="heart h1"></div>
    <div class="heart h2"></div>
    <div class="heart h3"></div>
    <div class="heart h4"></div>

    <div class="reference-page-header">
        <h2>
           Local Resources:
        </h2>
        <div class="links">
            <p>
                Looking to adopt or volunteer with a local rescue?
                
            </p>
            <div class="resc-links">
    
                <a href="https://otatpdx.org/" target="_blank">
                    One Tail at a Time
                </a>
                
                <a href="https://streetsavvydogrescue.org/" target="_blank">
                    Street Savy Dog Rescue
                </a>
                
                <a href="https://www.familydogsnewlife.org/" target="_blank">
                    Family Dog New Life
                </a>
                
            </div>
            
        </div>    
    </div>

    
    <div class="reference-page-header ">
        <h2>References and Helpful Sites</h2>

        <div class="more-links">
                
            <a href="https://positively.com/victorias-blog/balanced-dog-training-theres-nothing-balanced-about-it/">
                Victorias Blog: Balanced Dog Training
            </a>
            
            <a href="https://www.whyanimalsdothething.com/the-damage-of-dog-whispering?fbclid=IwAR0MPajHCmeVL4xaE7QIZcBJdqtuFQlphe0Kk9eWxPt32AYxd-c1qi4GHQc">
                The Damage of Dog Whispering
            </a>
            
            <a href="https://www.patriciamcconnell.com/learning-center">
                Patricia Mcconnell Learning Center
            </a>        
            
            <a href="https://www.dogbreedinfo.com/abc.htm">
                Dog Breed Info.com
            </a>
            
            <a href="http://www.nicolewilde.com/articles/">
                Nicole Wilde.com
            </a>
            
            <a href="https://www.dogwise.com/">
                Dogwise.com
            </a>
            
        </div>        
    </div>
        
        
</div>



{% endblock %}